config/routes.rb
Rails.application.routes.draw do
  get 'users/destroy'
  devise_for :users, controllers: {
    registrations: 'devise/registrations',
    sessions: 'sessions',
    confirmations: 'devise/confirmations',
    password: 'devise/password',
    omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'projects/entry'
  post 'projects/entry' => 'projects#create'
  delete 'projects/entry' => 'projects#destroy'
  get 'projects/:id', to: 'projects#show', as: 'projects_show'
  get 'projects/edit/:id', to: 'projects#edit', as: 'projects_edit'
  patch 'projects/edit/:id' => 'projects#update'
  get 'home', to: 'home#index'

  root 'users#index'
  get 'users', to: 'users#index'
  get 'users/setting', to: 'users#setting'
  delete 'users/setting' => 'users#destroy'
  # get 'users', to: 'users#index', as:'users'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :lockable, :timeoutable, :omniauthable, omniauth_providers: [:github]

  has_many :projects, foreign_key: :users_id, dependent: :destroy

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.username = auth.info.nickname # assuming the user model has a name
      user.display_name = auth.info.name
      user.github_token = auth.credentials.token
      # user.image = auth.info.image # assuming the user model has an image
      # If you are using confirmable and the provider(s) you use validate emails,
      # uncomment the line below to skip the confirmation emails.
      # user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    if session['devise.user_attributes']
      new(session['devise.user_attributes']) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])
    # result = RestClient.post('https://github.com/login/oauth/access_token',
    #                         {client_id: client_id,
    #                          client_secret: client_secret,
    #                          code: session_code,
    #                          state: state},
    #                          accept: :json)
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to home_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # 参考：https://qiita.com/tobita0000/items/866de191635e6d74e392
  #  before_action ~ で、ログイン済みのアカウントのみでしかアクセスできなくなる。
  before_action :authenticate_user!
  def index
    @projects = current_user.projects
    @recent_commit_logs = GithubCommitLog.where(users_id: current_user.id).last(3)
  end

  def show; end
  def setting; end


  def destroy
    print("\n  delete for user : #{current_user.username}  #{current_user.email}\n")
    @projects = current_user.projects
    @projects.each do |project|
      # 削除
      print("\n    project : #{project}    delete \n")
      project.github_commit_logs.destroy_all()
      project.delete()
    end
    current_user.delete()
    redirect_to home_path
  end

end

app/views/users/index.html.erb
<div class = "hs-user">

  <div class="hs-user--header">
    <div class = "has-logo">
      <a href="<%= url_for(home_path) %>">
        <h1>HAS</h1>
      </a>
    </div>
    <div class = "button-project">
      <a class="page__plus-btn" href="<%= url_for(projects_entry_path) %>"><div></div><div></div></a>
    </div>
  </div>

  <div class = "hs-users-sidebar-wrapper">
    <!-- 左側：ユーザー情報 -->
    <div class = "hs-users-sidebar">
        <div class = "user-photo">
          <%= image_tag('syu-ru_yagi_user.png') %>
        </div>
        <div class = "user-name">
          <h1><%= current_user.username %></h1>
        </div>

        <div class = "button-area">
          <div class = "button-logout">
            <%= link_to users_setting_path  do %>
            <button class="ui button" >
              設定
            </button>
            <% end %>
          </div>
        </div>

        <div class = "button-area">
          <div class = "button-logout">
            <a href="https://docs.google.com/forms/d/1mc3KoMz5BBqCpp3uJmdY8phnxNnFovQPVGSf7GV2hsQ">
            <button class="ui button" >
              レビュー
            </button>
            </a>
          </div>
        </div>

        <%= link_to destroy_user_session_path, method: :delete do %>
        <div class = "button-area">
          <div class = "button-logout">
            <button class="ui button logout" >
              ログアウト
            </button>
          </div>
        </div>
        <% end %>
      </div>
    <!-- 右側：プロジェクト一覧 -->
      <div class = "hs-users-main_contents">
        <div class = "hs-users-renewal">
          <!--ここに更新状況を書く-->
          <h2>更新状況</h2>
          <p>
            <% @recent_commit_logs.reverse_each do |log| %>
              <div class="aa" >
                <%= log.message %>
              </div><br>
            <% end %>
          </p>
        </div>

        <div class = "hs-project-pictures-wrapper">
          <div class = "hs-users-table-project">
            <div class="hs-m--table normal">
              <h2 class="list_title">プロジェクト一覧</h2>
              <div class="projects_flame">
                <table>
                  <thead>
                    <tr>
                      <th width="230">プロジェクト名</th>
                      <th width="30">エサ</th>
                      <th width="50">次の更新</th>
                      <th width="30">実績</th>
                      <th width="30">削除</th>
                      <th width="30">編集</th>
                      <th width="30">累計</th>
                      <th width="40">連続記録(現在)</th>
                      <th width="40">連続記録(最高)</th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @projects.reverse_each do |t| %>
                      <tr>
                        <td><a href="https://github.com/<%= t.owner %>/<%= t.name %>/">
                          <div class = "project_name">
                            <%= t.name %>
                          </div>
                        </a>
                        </td>
                        <td>
                          <%= t.commit_num %>
                        </td>
                        <td>
                          <%= t.day_counter %> 日後 <br>AM9:00
                        </td>
                        <td>
                          <%= link_to projects_show_path(t) do %>
                            <i class="trophy icon">
                            </i>
                          <% end %>
                        </td>
                        <td>
                          <%= link_to projects_entry_path(project_id: t.id), method: :delete do %>
                            <div class="delete">
                              <i class="trash alternate icon"></i>
                            </div>
                          <% end %>
                        </td>
                        <td>
                          <%= link_to projects_edit_path(id: t.id) do %>
                          <div class="change">
                            <i class="edit icon"></i>
                          </div>
                          <% end %>
                        </td>
                        <td>
                          <%= t.commit_sum %>
                        </td>
                        <td>
                          <%= t.sprint_continue_tmp %>
                        </td>
                        <td>
                          <%= t.sprint_continue_record %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
          <!--div class = "hs-users-pictures">
            <h2 class="list_title">獲得絵画</h2>
            <div class = "pictures">
              <%= image_tag('Mojiyagi.png') %>
            </div>
          </div-->
        </div>
    </div>
  </div>

</div>

app/views/users/setting.html.erb
<div class = "hs-m--project">
  <div class="page__bg"></div>
  <div class="page__decoration"></div>
  <div class="page__inner">
    <div class = "hs-project">
      <p> 通知先のメールアドレス </p>
      <!-- 文字がずれてたので応急処置 -->
      <%= current_user.email %>
      <br><br>

      <p> アカウントを削除する </p>
      <div>ユーザー情報を全て削除、初期化します。<br>
        一度削除すると、元には戻せません。
      </div>
      <br>
  　<!--  ← スペース（全角）  -->
      <!-- ただのダイアログで見てくれが悪いので、UI を少しいじってほしい！
          良さそうな参考：https://qiita.com/ihatov08/items/a0b3b043ba809fdc2cd6 -->
      <%= link_to "削除する", users_setting_path, method: :delete,
          data: {
            title: "削除の確認",
            confirm: "一度削除すると、元には戻せません。\n本当によろしいですか？"
          }, class: "ui button"%>
      <!--button class="ui button">
        解約する
      </button-->
      <a class="page__close-btn" href="<%= url_for(users_path) %>"><div></div><div></div></a>
    </div>
  </div>


</div>

app/views/users/show.html.erb
<h1>こんにちは、<%= current_user.username %>さん</h1>
<p>ユーザー用ページです。</p>