config/routes.rb
Rails.application.routes.draw do
  get 'users/destroy'
  devise_for :users, controllers: {
    registrations: 'devise/registrations',
    sessions: 'sessions',
    confirmations: 'devise/confirmations',
    password: 'devise/password',
    omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'projects/entry'
  post 'projects/entry' => 'projects#create'
  delete 'projects/entry' => 'projects#destroy'
  get 'projects/:id', to: 'projects#show', as: 'projects_show'
  get 'projects/edit/:id', to: 'projects#edit', as: 'projects_edit'
  patch 'projects/edit/:id' => 'projects#update'
  get 'home', to: 'home#index'

  root 'users#index'
  get 'users', to: 'users#index'
  get 'users/setting', to: 'users#setting'
  delete 'users/setting' => 'users#destroy'
  # get 'users', to: 'users#index', as:'users'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<div class="hs-m--hero">
  <div class="hs-hero--header" id = "hs-hero--header">
    <div class = "has-logo">
      <a href="<%= url_for(home_path) %>">
        <h1>HAS</h1>
      </a>
    </div>
    <div class="button-area">

      <% if user_signed_in? %>
        <div class="ui buttons">
          <%= link_to current_user.username, users_path, class: "buttonman" %>
          <div class="or"></div>
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "buttonman" %>
        </div>
      <% else %>
        <div class="ui buttons">
        <%= link_to 'Githubログイン', user_github_omniauth_authorize_path, class: "ui buttonman" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="topbox">
    <div class = "has-catchphrase">
      <h1>Let's grow Projects & Goats</h1>
    </div>

    <div class = "has-setumei">
      <p>ヤギを飼うように、あなたのプロジェクトを育てる</p>
    </div>

    <div class="button-area2">

      <% if user_signed_in? %>
          <a href="<%= url_for(users_path) %>" class="userbutton">
            <button class="ui inverted button">
            ユーザページ
            </button>
          </a>
      <% else %>
        <a href="<%= url_for(user_github_omniauth_authorize_path) %>">
          <button class="ui inverted button">
            Githubログインではじめる
          </button>
        </a>
      <% end %>
    </div>
    <div class = "learnmore-button">
      <i class="big angle double down icon"></i>learnmore
    </div>
  </div>
</div>

<div class = "hs-m--has_what">
  <div class= "has_what_title">
    HASってなに？
  </div>
  <div class = "has-setumei2">
    <p>
      HASは開発を楽しいものにする新しい仕組みです。<br>
      趣味で開発をしていると、目標の期限を先延ばしにしたりと<br>
      ついつい忘れがちになりませんか？<br>
      HASはそのようなあなたの悩みを解消します。<br>
      プロジェクトを進めることでヤギの実績が解除され，<br>
      あなたのプロジェクトも彩ることでしょう。
    </p>
  </div>
</div>

<div class = "hs-m--commit">
  <<div class= "has_pro_title">
    プロジェクトを登録するとヤギからの手紙が届きます
  </div>
  <div class = "userpage-setumei-wrapper">
    <div class = "has-setumei3">
      <p>
      手紙は進捗状況によって変化します。<br>
      プロジェクトが進んでいれば，<br>
      ヤギからの喜びの手紙が届きます。<br>
      <br>
      <br>
      一方でプロジェクトが<br>
        進んでいない場合は…
        </p>
    </div>
    <div class = "userpage-gazou">
      <%= image_tag('comiyagi_yama_mozs.png') %>
    </div>
  </div>
</div>




<!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>-->
<!-- <script src="app/assets/javascripts/header.js"></script> -->